# Generated by Django 5.0.7 on 2024-08-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_check_out_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_out_model',
            old_name='start',
            new_name='state',
        ),
        migrations.AddField(
            model_name='check_out_model',
            name='last_name',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='check_out_model',
            name='first_name',
            field=models.CharField(max_length=13),
        ),
    ]
