# Generated by Django 5.0.7 on 2024-08-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_start_check_out_model_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_list_model',
            name='order_payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders_list_model',
            name='order_razorpay_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders_list_model',
            name='order_signature_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
