# Generated by Django 5.0.7 on 2024-08-16 12:06

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orders_list_model_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_out_model',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
