# Generated by Django 5.0.7 on 2024-08-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_check_out_model_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_out_model',
            name='first_name',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
