# Generated by Django 5.0.7 on 2024-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_check_out_model_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_out_model',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
