# Generated by Django 5.0.7 on 2024-08-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_check_out_model_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_out_model',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
