# Generated by Django 5.0.7 on 2024-08-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_check_out_model_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_out_model',
            name='order_note',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
