# Generated by Django 5.0.7 on 2024-08-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
